import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [numbers, setNumbers] = useState([
    83, 1, 78, 26, 67, 54, 49, 7, 36, 99, 26, 19, 15, 7, 21, 39, 7, 2, 8,
  ]);
  const [sum, setSum] = useState(0);
  const [min, setMin] = useState(null);
  const [max, setMax] = useState(null);
  const [even, setEven] = useState([]);
  const [odd, setOdd] = useState([]);
  const [duplicates, setDuplicates] = useState([]);
  const [evenCount, setEvenCount] = useState(0);
  const [oddCount, setOddCount] = useState(0);

  const calculate = () => {
    let sum = 0;
    let min = numbers[0];
    let max = numbers[0];
    let even = [];
    let odd = [];
    let evenCount = 0;
    let oddCount = 0;

    for (let i = 0; i < numbers.length; i++) {
      sum += numbers[i];
      if (numbers[i] < min) {
        min = numbers[i];
      }
      if (numbers[i] > max) {
        max = numbers[i];
      }
      if (numbers[i] % 2 === 0) {
        even.push(numbers[i]);
      } else {
        odd.push(numbers[i]);
      }
      if (
        numbers.lastIndexOf(numbers[i]) !== i &&
        duplicates.indexOf(numbers[i]) === -1
      ) {
        duplicates.push(numbers[i]);
      }
      if (numbers[i] % 2 === 0) {
        evenCount++;
      } else {
        oddCount++;
      }
    }

    setSum(sum);
    setMin(min);
    setMax(max);
    setEven(even);
    setOdd(odd);
    setDuplicates(duplicates);
    setEvenCount(evenCount);
    setOddCount(oddCount);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={calculate}>Calculate</button>
        <p>Numbers: {numbers.join(", ")}</p>
        <p>Sum: {sum}</p>
        <p>Minimum: {min}</p>
        <p>Maximum: {max}</p>
        <p>Even: {even.join(", ")}</p>
        <p>Odd: {odd.join(", ")}</p>
        <p>Duplicates: {duplicates.join(", ")}</p>
        <p>Even Count: {evenCount}</p>
        <p>Odd Count: {oddCount}</p>
      </main>
    </>
  );
}
